[tools]
act = "latest"
action-validator = "latest"
actionlint = "latest"
atuin = "latest"
aws-cli = "2"
bat = "latest"
bottom = "latest"
chezmoi = "latest"
cosign = "latest"
delta = "latest"
dive = "latest"
docker-slim = "latest"
fzf = "latest"
gh = "latest"
go = "latest"
gum = "latest"
hadolint = "latest"
hugo = "latest"
hyperfine = "latest"
k9s = "latest"
kind = "latest"
lazydocker = "latest"
lazygit = "latest"
node = "22"
packer = "latest"
pre-commit = "latest"
pulumi = "latest"
python = "3.12"
ruff = "latest"
scaleway = "latest"
starship = "latest"
terraform = "latest"
uv = "latest"
yq = "latest"
zellij = "latest"
zoxide = "latest"
